language: generic 
os: 
  - linux
dist: xenial
services:
  - docker

before_install:
  - docker build -t yetiasg/vue-docker -f Dockerfile .

script:
  - docker run -e CI=true yetiasg/vue-docker