language: generic 
os: 
  - linux
dist: xenial
services:
  - docker

before_install:
  - docker build -t yetiasg/vue-docker -f Dockerfile.dev .

# script:
#   - docker run -e CI=true yetiasg/vue-docker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "vue-docker"
  env: "Vuedocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-531089319466"
  bucket_path: "vue-docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY