language: generic 
os: 
  - linux
dist: xenial
sudo: true
services:
  - docker

before_install:
  - docker build -t yetiasg/vue-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true yetiasg/vue-docker